---
title: "resume"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

JEONG YEON KIM
jeongkim@utexas.edu | 2501 Pearl St #303 Austin, TX 78705 | 214-998-4971 | jeongkim.netlify.com

EDUCATION
The University of Texas at Austin		Bachelor of Science and Arts in Biology, Honors				   May 2021
					Business of Healthcare Certificate 
					GPA: 3.93
					Health Science Scholar

EXPERIENCE
Freshman Research Initiative (FRI): Functional Genomics – Peer Mentor; Austin, TX				 Aug 2018 – Present
• Taught new FRI students essential lab techniques and protocols
• Supervised students in lab experiments and aided in project development

Varsity Tutors – SAT/ACT Tutor; Austin, TX								  Jan 2019 – Present
• Tutored students in SAT and ACT 

Peer-Led Undergraduate Studying (PLUS) Facilitator – Discussion Leader; Austin, TX			             Jan 2019 – May 2019
• Led students in weekly discussions over the learning material in Biochemistry course
• Discussed learning material weekly with professor and other peer coordinators

ACADEMIC PROJECTS
Freshman Research Initiative (FRI): Functional Genomics – Undergraduate Researcher; Austin, TX	            Spring 2018 – Present
• Utilized molecular biology techniques such as CRISPR/Cas9 and recombinant DNA technology to genetically modify yeast
• Humanized yeast cells (S. cerevisiae) by systematically replacing the Swr1 yeast gene with the EP400 human histone variant gene 
• Determined the functional viability of the human EP400 gene as a substitute to the Swr1 yeast gene via phenotypic screening

Freshman Research Initiative (FRI): Summer Research Fellowship – Summer Fellow; Austin, TX		           Summer 2018
• Continued independent research project from the Functional Genomics Stream
• Transformed yeast by replacing yeast histone genes with their corresponding human histone variants

LEADERSHIP EXPERIENCE AND ACTIVITIES
Texas Pre-Dental Society – Member and Volunteer; Austin, TX						  Fall 2017 – Present
• Professional pre-dental student organization that prepares students for dental school
• Attended presentations from speakers in the dental field, including Dean of Admissions of dental schools, local Austin dentists, and dental volunteering advocates
• Volunteered for various opportunities in the local community offered by Texas Pre-Dental Society

Texas Missions of Mercy (TMOM) – Volunteer; Austin, TX							           Summer 2018
• Provided dental care to the uninsured population of Austin to serve their needs
• Assisted dentists in makeshift dental clinic and interacted with patients

Texas Healthy Habits – Treasurer; Austin, TX							            Spring 2018 – Present
• Presented to elementary and preschool children in the Austin area about public health and dental health
• Informed students about healthy living habits

Global Medical Missions Alliance – Member and Volunteer; Austin, TX			                       Fall 2017 –  Spring 2019
• Attended a medical mission trip to Zaragoza, Mexico and provided free medical and dental care
• Assisted dentist in the dental clinic and served the needs of the patient

Shadowed Dentists										            Spring 2018 – Present
• Dr. R. Shad Hattaway, DDS – 29 hrs
• Dr. Jae Yoon, DDS – 17 hrs
• Dr. Jim Tyree, DDS – 14 hrs
• Dr. Christina Walker, DDS – 

Micah 6 Food Pantry – Volunteer; Austin, TX								  Fall 2017 – Present 
• Distributed food and groceries to the homeless and impoverished population of Austin

Sandy Lake Rehabilitation and Care Center – Volunteer; Coppell, TX					           Summer 2017
• Assisted and interacted with the elderly patients receiving end-of-life care in the nursing home
• Coordinated weekly events with the event planner 

HONORS
• Health Science Scholar											  Fall 2017 – Present
• University Honors										        Fall 2017  – Spring 2019
• CNS Academic Scholarship									         Fall 2017 – Spring 2018
• National AP Scholar

ADDITIONAL INFORMATION
Computer Skills: R Studio, Python, MS Excel, Word, PowerPoint, Canva
Languages: Fluent in Korean
Work Eligibility: Eligible to work in the U.S. with no restrictions
